routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('auth')->group( function () {
    Route::get('/', function () {
        return redirect()->route('dashboard');
    });
    Route::prefix('/user')->group(function () {
        Route::get('/dashboard', [UserController::class, 'dashboard'])->name('dashboard');

        Route::prefix('/orders')->group(function () {
            Route::get('/', [OrderController::class, 'all'])->name('orders');
            Route::get('/create', [OrderController::class, 'create'])->name('orders.create');
            Route::post('/create', [OrderController::class, 'store']);
            Route::get('/{order}', [OrderController::class, 'show'])->name('orders.show')->middleware('order.user');
        });
        Route::prefix('/payment')->group(function () {
            Route::post('/{order}', [PaymentController::class, 'startPayment'])->name('orders.payment')->middleware('order.user');
            Route::get('/{order}/verify', [PaymentController::class, 'verifyPayment'])->name('orders.payment-verify');
        });
    });
});

Route::get('/login', [AuthController::class, 'loginForm'])->name('login');
Route::post('/login', [AuthController::class, 'login']);
Route::post('/logout', [AuthController::class, 'logout'])->name('logout');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'email_verified_at',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * @return HasMany
     */
    public function orders(): HasMany
    {
        return $this->hasMany(Order::class);
    }

    /**
     * @return HasMany
     */
    public function creditCards(): HasMany
    {
        return $this->hasMany(CreditCard::class);
    }

    public function getVerifiedCardAttribute()
    {
        return CreditCard::where([
            'user_id' => $this->id,
            'status'  => CreditCard::STATUS_VERIFIED,
        ])->first();
    }
}

resources/views/bank_redirect_form.blade.php
@extends('layouts.main')

@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                در حال انتقال به درگاه در یک ثانیه
            </div>
        </div>
        <div id="my-form">
            <form method="{{ $form['method'] }}" action="{{ $form['action'] }}" id="payment-form">
                @csrf
                @foreach($form['parameters'] as $key => $value)
                    <input type="text" name="{{ $key }}" value="{{ $value }}" hidden>
                @endforeach
                <button type="submit" class="btn btn-primary">هم اکنون برو</button>
            </form>
        </div>
    </div>
@endsection

@push('script')
    <script>
        // Wait for 3 seconds before submitting the form
        setTimeout(function() {
            document.getElementById('payment-form').submit().disabled = true;
        }, 1000);
    </script>
@endpush

resources/views/dashboard.blade.php
@extends('layouts.main')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        میزکار
                    </div>
                    <div class="card-body">
                        <h5>سلام {{ $user->name }} خوش آمدید </h5>
                        <p>شما با ایمیل {{ $user->email }} وارد شده اید. </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-md-6">
                <a href="{{ route('orders') }}" class="btn btn-primary btn-block">سفارشات</a>
            </div>
            <div class="col-md-6">
                <form id="logout-form" action="{{ route('logout') }}" method="POST">
                    @csrf
                    <button class="btn btn-danger btn-block" type="submit">خروج</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/errors.blade.php
@extends('layouts.main')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">!!!!!خطا!!!!!</div>

                    <div class="card-body">
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button onclick="window.history.back();" class="btn btn-primary">بازگشت</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/login.blade.php
@extends('layouts.main')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">ورود به حساب کاربری</div>
                    <div class="card-body">
                        <form action="{{ route('login') }}" method="POST">
                            @csrf
                            <div class="mb-3">
                                @error('credentials')
                                <div class="alert-danger">
                                    <strong>{{ $message }}</strong>
                                </div>
                                @enderror
                            </div>
                            <div class="mb-3">
                                <label for="email" class="form-label">ایمیل</label>
                                <input type="email" class="form-control @error('credentials') is-invalid @enderror" id="email" name="email" placeholder="youremail@address.com" value="{{ old('email') }}" required autocomplete="email" autofocus>
                            </div>
                            <div class="mb-3">
                                <label for="password" class="form-label">گذرواژه</label>
                                <input type="password" class="form-control @error('credentials') is-invalid @enderror" id="password" name="password" placeholder="********" autocomplete="current-password" required>
                            </div>
                            <div class="d-grid">
                                <button class="btn btn-primary">ورود</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/order_detail.blade.php
@extends('layouts.main')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        جزئیات سفارش
                    </div>
                    <div class="card-body">
                        <ol>
                            <li><p>سفارش شماره: {{ $order->id }}</p></li>
                            <li><p>توضیحات سفارش: {{ $order->description }}</p></li>
                            <li><p>مبلغ سفارش: {{ number_format($order->amount) }} ریال</p></li>
                            @if($order->status == \App\Models\Order::STATUS_INIT)
                            <li><p class="alert-danger">شماره کارت معرفی شده کاربر برای واریز وجه <br><strong>{{ $order->user->verified_card->card_number }}<br></strong> می‌باشد و پرداخت فقط با این شماره کارت‌ مورد قبول است.</p></li>
                            @elseif($order->status == \App\Models\Order::STATUS_PAYED)
                                <li><p class="alert-success">سفارش در حال انجام است.</p></li>
                            @elseif($order->status == \App\Models\Order::STATUS_FINISHED)
                                <li><p class="alert-success">سفارش با موفقیت خاتمه یافته است.</p></li>
                            @elseif($order->status == \App\Models\Order::STATUS_CANCELED)
                                <li><p class="alert-danger">سفارش کنسل شده است.</p></li>
                            @endif
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        @if($order->status == \App\Models\Order::STATUS_INIT)
        <div class="card">
            <div class="card-header">پرداخت سفارش</div>
            <div class="card-body">
                <form action="{{ route('orders.payment', $order->id) }}" method="POST">
                    @csrf
                    <div class="mb-3">
                        @error('gateway')
                        <div class="alert-danger">
                            <strong>{{ $message }}</strong>
                        </div>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <input type="radio" class="form-check-input @error('gateway') is-invalid @enderror" id="gateway" name="gateway" placeholder="youremail@address.com" value="paystar" required checked>
                        <label for="gateway" class="form-check-label">درگاه پی‌استار</label>
                    </div>
                    <div class="d-grid">
                        <button class="btn btn-primary">پرداخت</button>
                    </div>
                </form>
            </div>
        </div>
        @endif
    </div>
@endsection

resources/views/orders.blade.php
@extends('layouts.main')

@section('content')
    <div class="container">
        <div class="row mb-3">
            <div class="col-md-12">
                <a href="{{ route('orders.create') }}" class="btn btn-success">سفارش جدید</a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">سفارشات من</div>

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>شماره سفارش</th>
                                    <th>توضیحات</th>
                                    <th>وضعیت</th>
                                    <th>مبلغ(ریال)</th>
                                    <th>جزئیات</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($orders as $order)
                                    <tr>
                                        <td>{{ $order->id }}</td>
                                        <td>{{ $order->description }}</td>
                                        <td>
                                            @switch($order->status)
                                                @case(\App\Models\Order::STATUS_INIT)
                                                    ثبت شده(در انتظار پرداخت)
                                                    @break
                                                @case(\App\Models\Order::STATUS_PAYED)
                                                    پرداخت شده(در حال اجرا)
                                                    @break
                                                @case(\App\Models\Order::STATUS_FINISHED)
                                                    خاتمه یافته
                                                    @break
                                                @case(\App\Models\Order::STATUS_CANCELED)
                                                    لغو شده
                                                    @break
                                            @endswitch
                                        </td>
                                        <td>{{ number_format($order->amount) }}</td>
                                        <td>
                                            <a href="{{ route('orders.show', $order->id) }}" class="btn btn-primary">جزئیات</a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/orders_create.blade.php
@extends('layouts.main')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">ثبت سفارش جدید</div>
                    <div class="card-body">
                        <form action="{{ route('orders.create') }}" method="POST">
                            @csrf
                            <div class="mb-3">
                                @error('description')
                                <div class="alert-danger">
                                    <strong>{{ $message }}</strong>
                                </div>
                                @enderror
                                <label for="description" class="form-label">توضیحات سفارش</label>
                                <input type="text" class="form-control @error('description') is-invalid @enderror" id="description" name="description" placeholder="خدمت مورد نیاز شما ..." value="{{ old('description') }}" required>
                            </div>
                            <div class="mb-3">
                                @error('amount')
                                <div class="alert-danger">
                                    <strong>{{ $message }}</strong>
                                </div>
                                @enderror
                                <label for="amount" class="form-label">مبلغ پرداختی</label>
                                <input type="number" class="form-control @error('amount') is-invalid @enderror" id="amount" name="amount" placeholder="10000000" required>
                            </div>
                            <div class="d-grid">
                                <button class="btn btn-primary">ثبت سفارش</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/payment_result.blade.php
@extends('layouts.main')

@section('content')
    <div class="container">
        <h1>نتیجه تراکنش</h1>
        <div class="row">
            @if($result)
            <div class="col-md-6 alert-success">
                <h2>تراکنش موفق</h2>
                <p class="lead">سفارش شما در حال اجرا می باشد.</p>
            </div>
            @else
                <div class="col-md-6 alert-danger">
                    <h2>تراکنش ناموفق</h2>
                    <p class="lead">در صورت کسر شدن وجه از حساب شما، مبلغ طی ۷۲ ساعت آینده به حساب شما باز می گردد.</p>
                </div>
            @endif
        </div>
        <div class="row mt-4">
            <div class="col-md-12 text-center">
                <a href="{{ route('orders.show', $orderId) }}" class="btn btn-primary">بازگشت به سفارش</a>
            </div>
        </div>
    </div>
@endsection